---
- name: Install NTP package
  apt:
    name: ntp
    state: present

- name: Configure NTP servers
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: Restart NTP service

- name: Set up cron job for NTP synchronization
  cron:
    name: "Sync time with NTP servers"
    minute: 0
    hour: 0
    job: "ntpdate -u {{ ntp_servers | join(' ') }}"